# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "sapphire"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

robots = "index, follow"
fingerprintAlgorithm = "sha256"

[header]
  layout = "hybrid" # valid options: basic, hamburger, custom
  logoDark = "logo-day-mode.png"
  logo = "logo-night-mode.png"
  showTitle = false

[footer]
  showCopyright = true
  showThemeAttribution = true
  showScrollToTop = true
  showAppearanceSwitcher = false

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 5

[author]
name = "Amine LOUHICHI"
image = "avatar.jpeg"
headline = "Mon petit mémo des expertises partagées : Devops, GNU/Linux🐧, Architecture Applicative & Cie"
bio = "Mon petit mémo des expertises partagées : Devops, GNU/Linux🐧, Architecture Applicative & Cie"
links = [
  { email = "mailto:mfauwxs1b@mozmail.com" },
  { gitlab = "https://gitlab.com/aminelch" },
  { dev = "https://dev.to/aminelch" },
  { twitter = "https://twitter.com/aminelch" },
  { linkedin = "https://linkedin.com/in/aminelch" },
]

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/aminelch/aminelch.github.io/blob/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showComments = false
  sharingLinks = ["email", "dev.to", "reddit", "facebook", "twitter", "linkedin"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
